name: "titanrepo_go"

on:
  workflow_dispatch:
  schedule:
    # "Everyday at 12:00 UTC (5:00 PT)" https://crontab.guru/#0_12_*_*_*
    - cron: "0 12 * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      has_changes: ${{ steps.status.outputs.has_changes }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Titanrepo integration tests changes
        id: titanrepo_integration
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            titanrepo-tests/integration/**
            titanrepo-tests/helpers/**

      - name: Examples related changes
        id: examples
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            examples/**
            titanrepo-tests/example-*/**
            titanrepo-tests/helpers/**
            !**.md
            !**.mdx

      - name: Titanrepo JS Package related changes
        id: titanrepo_js
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            packages/**

      - name: Docs related changes
        id: docs
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            docs/**

      - name: Formatting related changes
        id: format
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/*.{yml,yaml,md,mdx,js,jsx,ts,tsx,json,toml,css}

    outputs:
      rust: ${{ steps.ci.outputs.diff != '' || steps.rust.outputs.diff != '' }}
      cargo_only: ${{ steps.ci.outputs.diff != '' || (steps.cargo.outputs.diff != '' && steps.titanpack.outputs.diff == '' && steps.titanrepo_rust.outputs.diff == '') }}
      # We only test workspace dependency changes on main, not on PRs to speed up CI
      cargo_on_main: ${{ steps.ci.outputs.diff != '' || (steps.cargo.outputs.diff != '' && github.event_name == 'push' && github.ref == 'refs/heads/main') }}
      titanpack: ${{ steps.ci.outputs.diff != '' || steps.titanpack.outputs.diff != '' }}
      titanpack_typescript: ${{ steps.ci.outputs.diff != '' || steps.titanpack_typescript.outputs.diff != '' }}
      titanrepo_rust: ${{ steps.ci.outputs.diff != '' || steps.titanrepo_rust.outputs.diff != '' }}
      titanpack_bench: ${{ steps.ci.outputs.diff != '' || steps.titanpack_bench.outputs.diff != '' }}
      titanrepo_go_unit: ${{ steps.ci.outputs.diff != '' || steps.titanrepo_go.outputs.diff != '' || steps.titanrepo_rust.outputs.diff != '' }}
      titanrepo_go_lint: ${{ steps.ci.outputs.diff != '' || steps.titanrepo_go.outputs.diff != ''}}
      titanrepo_build: ${{ steps.ci.outputs.diff != '' || steps.titanrepo_go.outputs.diff != '' || steps.titanrepo_rust.outputs.diff != '' || steps.titanrepo_integration.outputs.diff != ''}}
      titanrepo_integration: ${{ steps.ci.outputs.diff != '' || steps.titanrepo_go.outputs.diff != '' || steps.titanrepo_rust.outputs.diff != ''  || steps.titanrepo_integration.outputs.diff != '' }}
      examples: ${{ steps.ci.outputs.diff != '' || steps.examples.outputs.diff != '' || steps.titanrepo_version.outputs.diff != '' }}
      titanrepo_js: ${{ steps.ci.outputs.diff != '' || steps.titanrepo_js.outputs.diff != '' }}
      docs: ${{ steps.ci.outputs.diff != '' || steps.docs.outputs.diff != '' }}
      format: ${{ steps.ci.outputs.diff != '' || steps.format.outputs.diff != '' }}
      push: ${{ steps.ci.outputs.diff != '' || github.event_name == 'push' }}
      tag: ${{ steps.ci.outputs.diff != '' || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/node-file-trace')) }}
      main_push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      tag_push: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/node-file-trace') }}

  build_titanrepo:
    name: Build Titanrepo
    needs: determine_jobs
    if: needs.determine_jobs.outputs.titanrepo_build == 'true'
    runs-on: ${{ matrix.os.runner }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: ubuntu
            runner:
              - "self-hosted"
              - "linux"
              - "x64"
              - "metal"
          - name: macos
            runner: macos-latest
          - name: windows
            runner: windows-latest
